// TOAST
export const SHOW_TOAST = "SHOW_TOAST"

// MODALS
export const LOGIN_MODAL = "LOGIN_MODAL";
export const REGISTER_MODAL = "REGISTER_MODAL";
export const FORGOT_MODAL = "FORGOT_MODAL";
export const RESET_PASSWORD_MODAL = "RESET_PASSWORD_MODAL";
export const BOOK_LOTTERY_MODAL = 'BOOK_LOTTERY_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const USERSETTINGS_MODAL = 'USERSETTINGS_MODAL'
export const CHANGE_PASSWORD_MODAL = 'CHANGE_PASSWORD_MODAL'
export const MY_BOOKINGS_LOTTERY_MODAL = 'MY_BOOKINGS_LOTTERY_MODAL'

//Auth Actions
export const LOGIN_RESPONSE = "LOGIN_RESPONSE"
export const REGISTER_RESPONSE = "REGISTER_RESPONSE"
export const SOCIAL_LOGIN_RESPONSE = "SOCIAL_LOGIN_RESPONSE"
export const FORGOT_RESPONSE = "FORGOT_RESPONSE"
export const RESET_PASSWORD_RESPONSE = "RESET_PASSWORD_RESPONSE"
export const VERIFY_OTP_RESPONSE = "VERIFY_OTP_RESPONSE"
export const VALIDATE_OTP_RESPONSE = "VALIDATE_OTP_RESPONSE"
export const RESEND_OTP_RESPONSE = "RESEND_OTP_RESPONSE"
export const LOGOUT = "LOGOUT"
export const CHANGE_PASSWORD = "CHANGE_PASSWORD"
export const USER_TOKEN = "USER_TOKEN"

export const GET_ALL_INTERESTS = "GET_ALL_INTERESTS"
export const GET_ALL_CONNECTION = "GET_ALL_CONNECTION"
export const GET_YOUR_INTERESTS = "GET_YOUR_INTERESTS"
export const GET_IMAGES_GALLERY = "GET_IMAGES_GALLERY"
export const GET_USER_DATA = "GET_USER_DATA"
export const GET_HOME_DATA = "GET_HOME_DATA"
export const GET_OTHER_USER_DATA = "GET_OTHER_USER_DATA"
export const GET_SENT_REQUEST_DATA = "GET_SENT_REQUEST_DATA"
export const GET_RECEIVED_REQUESTS_DATA = "GET_RECEIVED_REQUESTS_DATA"
export const GET_MY_CONNECTION_LIST = "GET_MY_CONNECTION_LIST"
export const GET_PROFILE_VERIFICATION_POSES = "GET_PROFILE_VERIFICATION_POSES"
export const GET_USER_BY_LOCATION = "GET_USER_BY_LOCATION"

// get_user_by_location

export const UPDATE_USER_INTERESTED = "UPDATE_USER_INTERESTED"
export const UPDATE_YOUR_INTERESTED = "UPDATE_YOUR_INTERESTED"
export const UPDATE_USER_CONNECTION = "UPDATE_USER_CONNECTION"
export const USER_PROFILE_UPDATE = "USER_PROFILE_UPDATE"
export const USER_PROFILE_IMAGE_UPDATE = "USER_PROFILE_IMAGE_UPDATE"
export const USER_PROFILE_FRIST_IMAGE_UPDATE = "USER_PROFILE_FRIST_IMAGE_UPDATE"


export const BLOCK_USER = "BLOCK_USER"
export const UNBLOCK_USER = "UNBLOCK_USER"
export const GET_BLOCK_USER_DATA = "GET_BLOCK_USER_DATA"
export const GET_FAQ_DATA = "GET_FAQ_DATA"

// export const UPDATE_USER_FCM_TOKEN = "UPDATE_USER_FCM_TOKEN"

// users
export const GET_DISCOVER = "GET_DISCOVER"


// Common Action
export const CALL_RESPONSE = "CALL_RESPONSE"

// Loader

export const SHOW_LOADER = "SHOW_LOADER"
export const SET_OTHER_USER_ID = "SET_OTHER_USER_ID"


